# Configs for aviadas.com

# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: "aviadas.com"
email: andas222@gmail.com
description: "Personal website for Avi Das. Home for my thoughts, projects, and more."
twitter_username: avidas
github_username: avidas
url: "https://new.aviadas.com"
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin: "dirt"
# Outputting
permalink: /:categories/:title/
paginate: 10 # amount of posts to show
paginate_path: /page:num/
timezone: US

include:
  - _pages
  - assets
  - index.html

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - TODO.md
  - README.md
  - "*.org"
  - "*ltximg*"

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

# settings for author profile
author:
  name   : "Avi Das"
  avatar : "/assets/images/profile_2.png"
  bio    : "Product driven software builder and technical leader. The driving narrative of my career is to make delightful & reliable products that improves the lives of end users."
  links:
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/aviadas/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/avidas"
    - label: "Threads"
      icon: "fab fa-fw fa-threads"
      url: "https://www.threads.net/@das.avi"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/avidas"

footer:
  links:
    - label: "Threads"
      icon: "fab fa-fw fa-threads"
      url: "https://www.threads.net/@das.avi"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/avidas"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

# comments by disqus
comments:
  provider: "disqus"
  disqus:
    shortname: "avidas"

# Google Analytics
analytics:
  provider: "google"
  google:
    tracking_id: "UA-42293414-1"

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
